#!/bin/bash

set -e

apt-get install -y python2.7 python-pip unzip build-essential gcc python-dev nginx

wget https://github.com/peterklipfel/rabbit_flask/archive/master.zip
unzip master.zip
cd rabbit_flask-master
pip install -r requirements.txt
cd ..

rm /etc/nginx/sites-enabled/default
sed s/theipaddress/`ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'`/ nginx.conf > api_nginx.conf
ln -s `pwd`/api_nginx.conf /etc/nginx/sites-enabled/api_nginx.conf

crontab -u root `pwd`/api_crontab

open-port 80/tcp



