#!/bin/bash

set -e

apt-get install -y python2.7 python-pip unzip build-essential gcc python-dev

wget https://github.com/peterklipfel/rabbit_flask/archive/master.zip
unzip master.zip
cd rabbit_flask-master
pip install -r requirements.txt
cd ..

